name: Rancher Set Deployment Image Action
description: >
  Set Deployment Image

inputs:
  server:
    description: "Server Addr"
    required: true
  skipTLSVerify:
    description: "Skip TLS Verify"
    required: false
    default: "false"
  token:
    description: "Bearer Token"
    required: true
  controller:
    description: "Controller of Workload"
    required: false
    default: "deployment"
  namespace:
    description: "Namespace"
    required: true
  workload:
    description: "Workload Name"
    required: true

  body:
    description: "Body for Patching Operation"
    required: false
    default: ""

  container:
    description: "Container Index Number"
    required: false
    default: "0"
  image:
    description: "Target Image"
    required: false
    default: ""

  maxPatchRetry:
    description: "Max Retry Times for Patching"
    required: false
    default: "5"
  wait:
    description: "Waiting Workload Ready"
    required: false
    default: "false"
  maxWaitDuration:
    description: "Max Wait Duration"
    required: false
    default: "5m"

runs:
  using: node20
  main: dist/index.js
