name: Rancher Set Deployment Image Action
description: >
  Set Deployment Image

inputs:
  server:
    description: "Server Addr"
    required: true
  skipTLSVerify:
    description: "Skip TLS Verify"
    required: false
  token:
    description: "Bearer Token"
    required: true
  controller:
    description: "Controller of Workload, default deployment"
    required: false
  namespace:
    description: "Namespace"
    required: true
  workload:
    description: "Workload Name"
    required: true

  template:
    description: "Template for Patching"
    required: false

  container:
    description: "Deployment Container Name"
    required: false
  image:
    description: "Target Image"
    required: false

  maxPatchRetry:
    description: "Max Retry, default 5"
    required: false
  wait:
    description: "Waiting Workload Ready"
    required: false
  maxWaitDuration:
    description: "Max Wait Duration, default 5m"
    required: false

runs:
  using: node20
  main: dist/index.js
